---
title: "Diandre' Mortality Script"
output: html_document
date: "2025-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r clear environment}
rm(list = ls())
```


```{r message=FALSE, warning=FALSE}

library(readxl)
library(ggplot2)
library(dplyr)
library("survminer")
theme_set(theme_classic())
library(summarytools)
library(readr)
library(GGally)
library(tidyverse)
library(lubridate)
library(writexl)
library(wesanderson)
library(tidyr)
library(hms)
library(paletteer)
library(zoo)
library(grid)
library(patchwork)

Mortality_All <- read_excel("C:/Users/annab/OneDrive/Desktop/Bass Mortality 2026.xlsx")
Mortality_CMAST <- read_excel("C:/Users/annab/OneDrive/Desktop/Bass Mortality 2026.xlsx", sheet = "CMAST")
Mortality_DUML <- read_excel("C:/Users/annab/OneDrive/Desktop/Bass Mortality 2026.xlsx", sheet = "DAF")
Mortality_Ward <- read_excel("C:/Users/annab/OneDrive/Desktop/Bass Mortality 2026.xlsx", sheet = "Ward Creek")
Mortality_Stump <- read_excel("C:/Users/annab/OneDrive/Desktop/Bass Mortality 2026.xlsx", sheet = "Stump Sound")

```



```{r}

# Add a Site column to each
Mortality_CMAST <- Mortality_CMAST %>% mutate(Site = "CMAST")
Mortality_Ward <- Mortality_Ward %>% mutate(Site = "Ward Creek")
Mortality_DUML <- Mortality_DUML %>% mutate(Site = "DUML")

```


```{r}
clean_data <- function(df) {
  df %>%
    mutate(
      # Force Mortality Count to numeric. 
      # This automatically turns "MISSING" and blanks into NA.
      `Mortality Count` = suppressWarnings(as.numeric(as.character(`Mortality Count`)))
    ) %>%
    # Optional: Filter out rows where Date or Mortality Count is NA to keep the plot clean
    filter(!is.na(`Mortality Count`) & !is.na(Date))
}
```


```{r}
# 4. Clean the data
cmast_clean <- clean_data(Mortality_CMAST)
ward_clean  <- clean_data(Mortality_Ward )
duml_clean   <- clean_data(Mortality_DUML)
stump_clean <- clean_data(Mortality_Stump)

all_mortality <- bind_rows(
  cmast_clean,
  ward_clean,
  duml_clean,
  stump_clean
)

all_mortality$Site <- factor(
  all_mortality$Site,
  levels = c("StumpSound", "CMAST", "DUML", "Ward Creek")
)

```


```{r}
#experiment

box_function <- function(dataframe, plot_title) {
  p <- dataframe %>%
    ggplot(aes(x = as.factor(Date), y = `Mortality Count`)) +
    geom_point(aes(color = GeneticStrand), size = 2) +
    scale_color_manual(
      values = c(
        "New River (NR): Diploids from UNCW" = "purple",
        "Triploids: Triploids purchased from Downeast Mariculture" = "#F1C40F",
        "Stump Sound (SS): Diploids from UNCW" = "orange",
        "Cedar Island (CI): Diploids from UNCW" = "blue"
      )
    ) +
    facet_wrap(~ Site, scales = "fixed", nrow = 1) +
    theme_classic() +
    labs(x = "Date", y = "Mortality Total", title = plot_title) +
    theme(
  axis.text.x = element_text(angle = 45, hjust = 1),
  legend.position = "bottom",
  legend.title = element_blank()
)
  
  return(p)
}

plot_function <- function(dataframe, plot_title) {
  p <- dataframe %>%
    ggplot(aes(x = as.factor(Date), y = `Mortality Count`)) +
    geom_boxplot(outlier.shape = NA, fill = "lightgray", width = 0.6) +
    geom_jitter(width = 0.1, alpha = 0.6) +
    geom_point(aes(color = GeneticStrand), size = 1) +
    scale_color_manual(
      values = c(
        "New River (NR): Diploids from UNCW" = "purple",
        "Triploids: Triploids purchased from Downeast Mariculture" = "#F1C40F",
        "Stump Sound (SS): Diploids from UNCW" = "orange",
        "Cedar Island (CI): Diploids from UNCW" = "blue"
      )
    ) +
    facet_wrap(~ Site, scales = "fixed", nrow = 1) +
    scale_x_discrete(expand = expansion(mult = c(0.02, 0.02))) +
    theme_classic() +
    labs(x = "Date", y = "Mortality Total", title = plot_title) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "bottom",
      legend.title = element_blank(),
      panel.spacing = unit(0.4, "lines")
    )
  
  return(p)
}

p1 <- box_function(all_mortality, "Mortality Across Farms")

print(p1)

p2 <- plot_function(all_mortality, "Mortality Across Farms")

print(p2)

# how about -- facet the sites so that they are all next to each other, reduce space in between each box. 

```




```{r}
plot_function <- function(dataframe, plot_title) {
  p <- dataframe %>%
    ggplot(aes(x = as.factor(Date), y = `Mortality Count`)) +
    geom_boxplot(outlier.shape = NA, fill = "lightgray") +
    geom_jitter(width = 0.2, color = "steelblue", alpha = 0.7) +
    geom_point(aes(color = GeneticStrand), size = 1) +
  scale_color_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "yellow",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
    theme_classic() +
    labs(x = "Date", y = "Mortality Total", title = plot_title) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  return(p)
}

###Environmental Variables 


# Random Forest Package to see which environmental variable predict the best

## Survivor ship % for each site, remaining oysters/initial total oysters

```


```{r}
survival_function <- function(dataframe, plot_title) {

  df_summary <- dataframe %>%
    dplyr::group_by(Date) %>%
    dplyr::summarise(
      mean_mortality = mean(`Mortality Count`, na.rm = TRUE),
      .groups = "drop"
    )

  p <- ggplot(dataframe, aes(x = as.factor(Date), y = `Mortality Count`)) +
    geom_boxplot(outlier.shape = NA, fill = "lightgray") +
    geom_jitter(width = 0.2, color = "steelblue", alpha = 0.7) +
    geom_line(
      data = df_summary,
      aes(x = as.factor(Date), y = mean_mortality, group = 1),
      color = "firebrick",
      linewidth = 1
    ) +
    geom_point(
      data = df_summary,
      aes(x = as.factor(Date), y = mean_mortality),
      color = "firebrick",
      size = 2
    )  +
    theme_classic() +
    labs(
      x = "Date",
      y = "Mortality Total",
      title = plot_title
    ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  return(p)
}


```

```{r}
box_function <- function(dataframe, plot_title) {
  p <- dataframe %>%
    ggplot(aes(x = as.factor(Date), y = `Mortality Count`)) +
    geom_point(aes(color = GeneticStrand), size = 2) +
  scale_color_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "#F1C40F",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
    theme_classic() +
    labs(x = "Date", y = "Mortality Total", title = plot_title) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  return(p)
}


###Possibly color code dots by Genetic Lines, might make another function for that

###Environmental Variables 


# Random Forest Package to see which environmental variable predict the best

## Survivor ship % for each site, remaining oysters/initial total oysters

```


```{r}
p1 <- plot_function(cmast_clean, "CMAST Mortality")

print(p1)
ggsave("cmastmortality.jpeg")
```

```{r}
cmast_genetics <- box_function(cmast_clean, "CMAST Genetic Strand Mortality")

print(cmast_genetics)
```




```{r}
cmast_survival <- survival_function(cmast_clean, "CMAST Mortality")


print(cmast_survival)
```





```{r message=FALSE, warning=FALSE}

p2 <- plot_function(ward_clean, "Ward Creek Mortality")
print(p2)


```

```{r}
ward_genetics <- box_function(ward_clean, "Ward Genetic Strand Mortality")

print(ward_genetics)
```






```{r}
ward_survival <- survival_function(ward_clean, "Ward Creek Mortality")


print(ward_survival)
```




```{r message=FALSE, warning=FALSE}
p3 <- plot_function(duml_clean, "DUML Mortality")
print(p3)

###Change Y Axis to 2 figures 2,4,6,etc

```


```{r}
duml_genetics <- box_function(duml_clean, "Duke Aqua Farm Strand Mortality")

print(duml_genetics)
```

```{r message=FALSE, warning=FALSE}
duml_survival <- plot_function(duml_clean, "DUML Mortality")
print(duml_survival)

###Change Y Axis to 2 figures 2,4,6,etc

```


```{r}
bagplot_function <- function(dataframe, plot_title) {
  p <- dataframe %>%
    ggplot(aes(x = as.factor(Date), y = `Mortality Count`, color = GeneticStrand)) +
    geom_boxplot(outlier.shape = NA, fill = "lightgray") +
    geom_jitter(width = 0.2, alpha = 0.7) +
    theme_classic() +
    labs(x = "Date", y = "Mortality Total", color = "Bag", title = plot_title) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  return(p)
}


```



##Stump Sound 

```{r}
p4 <- plot_function(stump_clean, "Stump Sound Mortality")

##Fix y axis so the months are in the same order

print(p4)
```



```{r}
stump_survival <- survival_function(stump_clean, "Stump Sound Mortality")


print(stump_survival)
```


```{r}
stump_genetics <- box_function(stump_clean, "Stump Sound Strand Mortality")

print(stump_genetics)
```



```{r message=FALSE, warning=FALSE}
GeneticCMAST_plot <- bagplot_function(cmast_clean, "CMAST Oyster Mortality
Over Time by Genetic Strand")
GeneticCMAST_plot


```



```{r message=FALSE, warning=FALSE}
GeneticDUML_plot <- bagplot_function(duml_clean, "DUML Oyster Mortality
Over Time by Genetic Strand")
GeneticDUML_plot


```

```{r message=FALSE, warning=FALSE}

GeneticWard_plot <- bagplot_function(ward_clean, "Ward Creek Oyster Mortality
Over Time by Genetic Strand")
GeneticWard_plot


```


```{r Stats Table Function All Together}

##Not split up by date

stats_function <- function(dataframe) {
  dataframe %>%
    group_by(GeneticStrand) %>%
    summarise(
      mean_mortality = mean(`Mortality Count`, na.rm = TRUE),
      sd_mortality   = sd(`Mortality Count`, na.rm = TRUE),
      min_mortality  = min(`Mortality Count`, na.rm = TRUE),
      max_mortality  = max(`Mortality Count`, na.rm = TRUE),
      .groups = "drop"
    )
}



```



```{r Stats Table Function by Date}


stats_datefunction <- function(dataframe) {
  dataframe %>%
    group_by(GeneticStrand, Date) %>%
    summarise(
      mean_mortality = mean(`Mortality Count`, na.rm = TRUE),
      sd_mortality   = sd(`Mortality Count`, na.rm = TRUE),
      min_mortality  = min(`Mortality Count`, na.rm = TRUE),
      max_mortality  = max(`Mortality Count`, na.rm = TRUE),
      .groups = "drop"
    )
}



```


```{r}
CMAST_StatsDate <- stats_datefunction(cmast_clean)

CMAST_StatsDate
```
 


```{r CMAST Mortality by Genetic Strain message=FALSE, warning=FALSE}

CMAST_Genetic <- ggplot(cmast_clean, aes(x = as.factor(Date), y = `Mortality Count`, fill = GeneticStrand)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "CMAST Mortality Total by Genetic Strain",
    x = "Date",
    y = "Mortality"
  ) +
  scale_fill_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "#F1C40F",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
  theme_minimal()

print(CMAST_Genetic)

###Stats table for genetic line

###July 9th, purple and yellow

```

```{r}
CMAST_Stats <- stats_function(cmast_clean)

CMAST_Stats
```


```{r}
CMAST_StatsDate <- stats_datefunction(cmast_clean)

CMAST_StatsDate
```



```{r message=FALSE, warning=FALSE, DUML Mortality by Genetic Strain message=FALSE}

DUML_Genetic <- ggplot(duml_clean, aes(x = as.factor(Date), y = `Mortality Count`, fill = GeneticStrand)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "DUML Mortality Total by Genetic Strain",
    x = "Date",
    y = "Mortality"
  ) +
  scale_fill_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "yellow",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
  theme_minimal()

print(DUML_Genetic)

### Change Y axis to different numbers (Possibly by 2s?) 

### Make Y Axis scales for each site

###Maybe change visualization of dates to read better (add more spacing maybe) 

###Error bars

```


```{r Ward Mortality by Genetic Strain message=FALSE, warning=FALSE}

Ward_Genetic <- ggplot(ward_clean, aes(x = as.factor(Date), y = `Mortality Count`, fill = GeneticStrand)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Ward Creek Mortality Total by Genetic Strain",
    x = "Date",
    y = "Mortality"
  ) +
  scale_fill_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "yellow",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
  theme_minimal()

print(Ward_Genetic)

###Need to look at excel file for July dates

### Clean up x-axis for better readability 

```

### Amy data is for Stump Sound Site 

```{r}
stump_clean$Date <- factor(
  stump_clean$Date,
  levels = c("Apr", "May", "June", "July", "Aug", "Sep", "Oct"),
  ordered = TRUE
)


```



```{r Ward Mortality by Genetic Strain message=FALSE, warning=FALSE}

Stump_Genetic <- ggplot(stump_clean, aes(x = as.factor(Date), y = `Mortality Count`, fill = GeneticStrand)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Ward Creek Mortality Total by Genetic Strain",
    x = "Date",
    y = "Mortality"
  ) +
  scale_fill_manual(
    values = c(
      "New River (NR): Diploids from UNCW" = "purple",
      "Triploids: Triploids purchased from Downeast Mariculture" = "yellow",
      "Stump Sound (SS): Diploids from UNCW" = "orange",
      "Cedar Island (CI): Diploids from UNCW" = "blue"
    )
  ) +
  theme_minimal()

print(Stump_Genetic)

###Need to look at excel file for July dates

### Clean up x-axis for better readability 

```



```{r Stats Table by Genetic Line}


stats_table <- stump_clean %>%
  group_by(GeneticStrand) %>%
  summarise(
    mean_mortality = mean(`Mortality Count`, na.rm = TRUE),
    sd_mortality   = sd(`Mortality Count`, na.rm = TRUE),
    min_mortality  = min(`Mortality Count`, na.rm = TRUE),
    max_mortality  = max(`Mortality Count`, na.rm = TRUE),
    .groups = "drop"
  )

stats_table

```

```{r Stats Table by Genetic Line & Date}


stats_table <- stump_clean %>%
  group_by(GeneticStrand, Date) %>%
  summarise(
    mean_mortality = mean(`Mortality Count`, na.rm = TRUE),
    sd_mortality   = sd(`Mortality Count`, na.rm = TRUE),
    min_mortality  = min(`Mortality Count`, na.rm = TRUE),
    max_mortality  = max(`Mortality Count`, na.rm = TRUE),
    .groups = "drop"
  )

stats_table

```


### Survivorship Code 
```{r}


#Load survivorship data
SurvivorshipSheet <- ("C:/Users/annab/OneDrive/Desktop/Survivorship25Renamed.xlsx")
SurvivorshipSheetWC <- read_excel(SurvivorshipSheet, sheet = "WC")
SurvivorshipSheetCMT <- read_excel(SurvivorshipSheet, sheet = "CMAST")
SurvivorshipSheetDAF <- read_excel(SurvivorshipSheet, sheet = "DAF")

SurvivorshipWC <- as.data.frame(SurvivorshipSheetWC)
SurvivorshipCMT <- as.data.frame(SurvivorshipSheetCMT)
SurvivorshipDAF <- as.data.frame(SurvivorshipSheetDAF)

```

```{r}

#Setting site and combining dataframes:
SurvivorshipWC$Source <- "WC"
SurvivorshipCMT$Source <- "CMT"
SurvivorshipDAF$Source <- "DAF"

S_Combined <- bind_rows(SurvivorshipWC, SurvivorshipCMT, SurvivorshipDAF)

```



```{r}


#Function to make the curves
Survivorship <- function(dframe) {
  splot = ggplot(dframe, aes(x = Date, y = Survivorship_Percent, color = Strain)) +  #Swap "Strain" to "Source" as needed
    ylim(0, 1) +
    geom_point() +
    #by site
    #scale_color_manual(values = c("CMT" = "darkgreen", "DAF" = "red", "WC" = "blue"))
    #by strain
    scale_color_manual(values = c("New River" = "purple", "Triploid" = "gold", "Stump Sound" = "orange", "Cedar Island" = "blue"))
  
  
  return(splot)
}


```


```{r}

#Example usage
NRCurve <-Survivorship(S_Combined[S_Combined$Strain == "New River",])

NRCurve

```



```{r}

#Example usage
TRIPLOIDCurve <-Survivorship(S_Combined[S_Combined$Strain == "Triploid",])

TRIPLOIDCurve

```


```{r}

#Example usage
StumpCurve <-Survivorship(S_Combined[S_Combined$Strain == "Stump Sound",])

StumpCurve

```








```{r}
Filtered_CMAST <- Mortality_CMAST %>%
  select(Date, 'Mortality Count', Site)

head(Filtered_CMAST)
```


```{r}
Filtered_DUML <- Mortality_DUML %>%
  select(Date, 'Mortality Count', Site)

head(Filtered_DUML)
```


```{r}
Filtered_Ward <- Mortality_Ward %>%
  select(Date, 'Mortality Count', Site)

head(Filtered_Ward)
```





```{r}

All_Mortality.df <- rbind(Filtered_CMAST, Filtered_DUML, Filtered_Ward)

head(All_Mortality.df)

```

```{r Plotting Mortality All Together}

All_Mortality.df %>%
  ggplot(aes(x = Date, y = 'Mortality Count', color = Site)) +
  geom_point() + 
  geom_line() + 
  labs(title = "Mortality Differences Between Sites",
       y = ("Date"),
       x = ("Mortality Total"),
       color = ("Site"))


```


```{r Plotting Mortality All Together}

All_Mortality.df %>%
  ggplot(aes(x = Date, y = 'Mortality Count', color = Site)) +
  geom_point() + 
  geom_line() + 
  labs(title = "Mortality Differences Between Sites",
       y = ("Date"),
       x = ("Mortality Total"),
       color = ("Site"))


```


